### ISSUE TITLE
Shader preprocessor fails under ASAN

### ISSUE THREAD

**Issue by w23** [w23/stameska#13]
```
==20871==ERROR: AddressSanitizer: stack-use-after-scope on address 0x7ffd905ebd60 at pc 0x00000043b064 bp 0x7ffd905eb7e0 sp 0x7ffd905eaf68
READ of size 5 at 0x7ffd905ebd60 thread T0
    #0 0x43b063 in memcmp /var/tmp/portage/portage/sys-libs/compiler-rt-sanitizers-7.0.1/work/compiler-rt-7.0.1.src/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc:827:7
    #1 0x59f9bb in std::char_traits<char>::compare(char const*, char const*, unsigned long) /usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/include/g++-v7/bits/char_traits.h:310:9
    #2 0x5c550d in std::basic_string_view<char, std::char_traits<char> >::compare(std::basic_string_view<char, std::char_traits<char> >) const /usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/include/g++-v7/string_view:268:14
    #3 0x5c14f3 in std::basic_string_view<char, std::char_traits<char> >::compare(char const*) const /usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/include/g++-v7/string_view:286:22
    #4 0x5be7cd in shader::Source::load(std::basic_string_view<char, std::char_traits<char> >) /home/steaream/proj/stameska/src/ShaderSource.cpp:60:17
    #5 0x58dac1 in PolledShaderSource::poll(unsigned int) /home/steaream/proj/stameska/src/PolledShaderSource.cpp:17:25
    #6 0x5860c0 in PolledShaderProgram::poll(unsigned int) /home/steaream/proj/stameska/src/PolledShaderProgram.cpp:18:32
    #7 0x6579c6 in VideoEngine::paint(unsigned int, int, int, float, Timeline&) /home/steaream/proj/stameska/src/VideoEngine.cpp:129:5
    #8 0x67d6cb in video_paint(float, Timeline&) /home/steaream/proj/stameska/src/video.cpp:37:13
    #9 0x679cfc in paint(unsigned int, float) /home/steaream/proj/stameska/src/tool.cpp:72:2
    #10 0x4f989b in main /home/steaream/proj/stameska/3p/atto/src/app_x11.c:264:5
    #11 0x7fe1c8489ae9 in __libc_start_main (/lib64/libc.so.6+0x21ae9)
    #12 0x420629 in _start (/home/steaream/proj/stameska/build/linux-x11-dbg-asan/stameska+0x420629)
```

**Comment by w23** [comment]
Fixed by #17
